logo: "/img/logo.png"
title: AudioWagon documentation
email: moleman1024dev@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  AudioWagon. Android Automotive OS USB music player
baseurl: "/audiowagon"
url: "https://moleman1024.github.io"
github_username: MoleMan1024
color_scheme: audiowagon
remote_theme: pmarsceill/just-the-docs
search_enabled: false
aux_links:
  "Source code on GitHub":
    - "//github.com/MoleMan1024/audiowagon/"
footer_content: "Copyright &copy; 2021 MoleMan1024"

